---
functional:
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен иметь мобильную версию.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - При клике на логотип сайта в хэдере, должна загружаться основная страница сайта
  - При добавлении товара в корзину, должно появляться поп-ап окно/ оповещение об успешном добавлении товара
